#! /bin/sh

# fixes render issues with java apps
wmname LG3D

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc config focus_follows_pointer true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a Peek state=floating
bspc rule -a Steam state=floating
