export PATH=$PATH:~/bin
export LANG="en_US.UTF-8"
export TERM="xterm-256color"
export EDITOR="vim"

if [[ "$OSTYPE" == "darwin" ]]; then
    export PATH=$PATH:/Library/TeX/texbin
    # homebrew directory
    export PATH=/usr/local/bin
fi

# extension specific

if [[ -f "${DOTDIR}/zsh/autoload/zshrc.python" ]]; then
    export PATH="${HOME}/.pyenv/bin:$PATH"
fi
