# Load Env
source "${HOME}/.zshenv"
export DOTDIR="${HOME}/.dotfiles"

# Added by Zplugin's installer
# only if things are autoloaded
if ls "${DOTDIR}/zsh/autoload/zshrc"* 1> /dev/null 2>&1; then
    source "$HOME/.zinit/bin/zinit.zsh"
    autoload -Uz _zinit
    (( ${+_comps} )) && _comps[zinit]=_zinit
fi

# load base files
# set vi command, load aliases...
for f in ${DOTDIR}/zsh/base/zshrc.*; do
    [ -e "$f" ] || continue;
      source "$f";
done

# load extensions
# if statement prevents error on empty dir
if ! [ -z "$(ls -A ${DOTDIR}/zsh/autoload/)" ]; then
    for f in ${DOTDIR}/zsh/autoload/zshrc.*
    do
        [ -e "$f" ] || continue;
        source "$f";
    done
fi
