### Added by Zplugin's installer
source '/home/ckl/.zplugin/bin/zplugin.zsh'
autoload -Uz _zplugin
(( ${+_comps} )) && _comps[zplugin]=_zplugin
### End of Zplugin's installer chunk

export DOTDIR="${HOME}/.dotfiles/"

# load base files
# set vi command, load aliases...
for f in ${DOTDIR}zsh/base/zshrc.*; do
    [ -e "$f" ] || continue;
    source "$f";
done

# load extensions
# if statement prevents error on empty dir
if ! [ -z "$(ls -A ${DOTDIR}zsh/autoload/)" ]; then
    for f in ${DOTDIR}zsh/autoload/zshrc.*
    do
        [ -e "$f" ] || continue;
        source "$f";
    done
fi
